_format_version: "3.0"
_transform: true

services:
- name: mockbin-service-1
  url: http://mockbin.com/request
  routes:
  - name: mockbin-url-1
    protocols:
    - "http"
    - "https"
    paths:
    - /
  plugins:
  - name: auth
    config:
      header_key: header_key

- name: example-service
  url: https://api.github.com/repos/kong/kong
  routes:
  - name: github-yaml
    protocols:
    - "http"
    - "https"
    paths:
    - /github
  plugins:
  - name: auth
    config:
      header_key: header_key

- name: pokemon
  url: https://pokeapi.co/api/v2/evolution-chain/67/
  routes:
  - name: pokemon-route
    protocols:
    - "http"
    - "https"
    paths:
    - /pokemon
  plugins:
  - name: auth
    config:
      header_key: header_key
