version: '3.9'
services: 
  kong-gateway:
    build: .
    container_name: kong-gateway
    environment:
      - KONG_DATABASE=off
      - KONG_PLUGINS=hello
      - KONG_PLUGINSERVER_NAMES=hello
      - KONG_PLUGINSERVER_HELLO_SOCKET=/usr/local/kong/hello.socket
      - KONG_PLUGINSERVER_HELLO_START_CMD=/usr/local/bin/hello
      - KONG_PLUGINSERVER_HELLO_QUERY_CMD=/usr/local/bin/hello -dump
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_HEADERS=off
    # command: "kong start -c /etc/kong/kong.conf"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"