apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: deployments/bets
    repoURL: https://github.com/codeedu/fc-api-gateway-k8s-bets-app.git
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-kong.yaml
  destination:
    namespace: bets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
