apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: address-api
  annotations:
    kubernetes.io/ingress.class: "kong"
    konghq.com/override: do-not-preserve-host
    konghq.com/plugins: hello-address,auth-address
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: financial-service
            port:
              number: 80
