apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus-bets
  annotations:
    kubernetes.io/ingress.class: "kong"
  labels:
    global: "true"
config: {}
plugin: prometheus
