@startuml kong-poc

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!define FONTAWESOME https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/font-awesome-5
!define AWSPuml https://raw.githubusercontent.com/awslabs/aws-icons-for-plantuml/v16.0/dist

!include AWSPuml/AWSCommon.puml
!include AWSPuml/Compute/Lambda.puml
!include AWSPuml/Database/DynamoDB.puml
!include DEVICONS/go.puml
!include DEVICONS/mongodb.puml
!include DEVICONS/apple.puml

left to right direction

System_Boundary(fluxo, "Kong PoC") { 
    Container(Apps, "Apps", "Contexto de consumidores da API", "Representação dos apps que utilizam as APIs", "HTTPS/JSON", )
    Container(Kong, "Kong API Gateway", "Gateway", "API Gateway responsável por direcionar requisições", "HTTPS/JSON")
    Lambda(ValidateAPIKey, "Check API Key", "Responsável por receber e validar API KEY")
    DynamoDB(APIKeyTable, "API KEY Table", "Responsável por armazenar API Keys")
    Container(APIs, "APIs", "Contexto de Banking", "Representação de APIs internas da Stone", "HTTPS/JSON")

    Rel(Apps, Kong, "Solicita visualização do extrato para", "HTTP/JSON")
    Rel_R(Kong, ValidateAPIKey, "Kong Plugin valida API-KEY para", "HTTP/JSON")
    Rel(ValidateAPIKey, APIKeyTable, "Recupera dado da API-KEY em", "HTTP/JSON")
    Rel(Kong, APIs, "Redireciona requisição para", "HTTP/JSON")
}

@enduml