name: CI-CD

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_USERNAME: jailtonjunior

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Verify dependencies
        working-directory: /plugins/auth
        run: go mod verify

      - name: Build
        working-directory: /plugins/auth
        run: go build -v ./...

      - name: Run go vet
        working-directory: /plugins/auth
        run: go vet ./...

      - name: Install staticcheck
        working-directory: /plugins/auth
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        working-directory: /plugins/auth
        run: staticcheck ./...

      - name: Install golint
        working-directory: /plugins/auth
        run: go install golang.org/x/lint/golint@latest

      - name: Run golint
        working-directory: /plugins/auth
        run: golint ./...

      - name: Run tests
        working-directory: /plugins/auth
        run: go test -race -vet=off ./...

      - name: Docker Login
        uses: docker/login-action@v1.9.0
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push 
        uses: docker/build-push-action@v2.4.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_USERNAME }}/kong-poc:latest
            ${{ env.DOCKER_USERNAME }}/kong-poc:2.0.0